### PR TITLE
P1 Personal Blog 

### PR DESCRIPTION
**Pull request by leemoispace**
It's the first project code of Udacity's Web Dev course: building a personal blog site. 

The link to project rubric:
https://learn-udacity.top/fewd586261/Front%20End%20Web%20Developer%20v5.0.0/Part%2002-Module%2001-Lesson%2006_Personal%20Blog%20Website/Project%20Rubric%20-%20Personal%20Blog%20Website.html

video:

https://user-images.githubusercontent.com/2882655/178235124-e352414a-53a4-4f1f-8800-bdc4c7de7777.mp4

### CODE REVIEW

**Comment by seb-lex** [comment]
Please change PR title to a more descriptive one.

**Comment by leemoispace** [comment]
done, thanks!

**Review by Martian2Lee — CHANGES_REQUESTED** [review]
please revert changes on "main" branch, and commit it to "p1-blog" branch

**Comment by leemoispace** [comment]
> please revert changes on "main" branch, and commit it to "p1-blog" branch

main reverted.
and add some new navigation style and commited.

**Comment by seb-lex** [comment]
Please host and link project on Codepen or similar and/or attach a screenshot of the completed project.

**Comment by leemoispace** [comment]
commit personal blog project

rubric: 
https://learn-udacity.top/fewd586261/Front%20End%20Web%20Developer%20v5.0.0/Part%2002-Module%2001-Lesson%2006_Personal%20Blog%20Website/Project%20Rubric%20-%20Personal%20Blog%20Website.htm

video:
https://user-images.githubusercontent.com/2882655/178200846-bf52e850-b1d8-4e8d-b07f-a1537703f88d.mp4

l

**Comment by seb-lex** [comment]
Video looks good. But please place this description in the beginning of the PR; where you have the "test" placeholder text:

https://github.com/leemoispace/Udacity-Front-End-WebDeveloper/pull/1#issue-1297272926

**Review by Martian2Lee — CHANGES_REQUESTED** [review]
please revert the starter code commit 
https://github.com/leemoispace/Udacity-Front-End-WebDeveloper/pull/1/commits/5934cc22a712871cf7a91e6e32c208d8d1d440d1

**Comment by leemoispace** [comment]
> Video looks good. But please place this description in the beginning of the PR; where you have the "test" placeholder text:
> 
> [#1 (comment)](https://github.com/leemoispace/Udacity-Front-End-WebDeveloper/pull/1#issue-1297272926)

Thanks. done.

**Comment by leemoispace** [comment]
> please revert the starter code commit [5934cc2](https://github.com/leemoispace/Udacity-Front-End-WebDeveloper/commit/5934cc22a712871cf7a91e6e32c208d8d1d440d1)

reverted and push from main branch.

**Review by seb-lex — APPROVED** [review]
All good.

**Review by Martian2Lee — APPROVED** [review]
🚀

**Pull request merged**
